In [1]:
import pandas as pd
import numpy as np
import requests # 크롤링
from selenium import webdriver # 크롤링
from selenium.webdriver.common.keys import Keys # 크롤링
from bs4 import BeautifulSoup # 크롤링
import warnings
warnings.filterwarnings(action='ignore') # Warning 무시
import googlemaps # 주소를 위도, 경도로 변환
from datetime import datetime
import re # 정규식

In [2]:
park_Gangnam = pd.read_csv('./data/서울특별시_강남구_도시공원_20210709_1625817293166_17363.csv', encoding= 'utf-8-sig')
park_Gangdong = pd.read_csv('./data/서울특별시_강동구_도시공원정보_20210825_1629872998632_15968.csv', encoding = 'utf-8-sig')
park_Gangbuk = pd.read_csv('./data/서울특별시_강북구_도시공원정보_20210824_1629982590816_8180.csv', encoding= 'utf-8-sig')
park_Gangseo = pd.read_csv('./data/서울특별시_강서구_도시공원정보_20210322_1616991304943_20133.csv', encoding= 'utf-8-sig')
park_Gwanak = pd.read_csv('./data/서울특별시_관악구_도시공원정보_20211015_1634617964680_12966.csv', encoding= 'utf-8-sig')
park_Gwangjin = pd.read_csv('./data/서울특별시_광진구_도시공원정보_20201211_1608529999233_8268.csv', encoding= 'utf-8-sig')
park_Guro = pd.read_csv('./data/서울특별시_구로구_도시공원정보_20210218_1613636520082_9690.csv', encoding= 'utf-8-sig')
park_Geumcheon = pd.read_csv('./data/서울특별시_금천구_도시공원정보_20210902_1630927108163_10424.csv', encoding= 'utf-8-sig')
park_Nowon = pd.read_csv('./data/서울특별시_노원구_도시공원정보_20210913_1631586982975_23533.csv', encoding= 'utf-8-sig')
park_Dobong = pd.read_csv('./data/서울특별시_도봉구_도시공원정보_20190101.csv', encoding= 'utf-8-sig')
park_Dongdaemun = pd.read_csv('./data/서울특별시_동대문구_도시공원정보_20210625_1624583959638_8588.csv', encoding= 'utf-8-sig')
park_Dongjak = pd.read_csv('./data/서울특별시_동작구_도시공원정보_20210429_1619684732418_7703.csv', encoding= 'utf-8-sig')
park_Mapo = pd.read_csv('./data/서울특별시_마포구_도시공원정보_20200709_1608170783985_13239.csv', encoding= 'utf-8-sig')
park_Seodaemun = pd.read_csv('./data/서울특별시_서대문구_도시공원정보_20210801_1627885751593_11799 (1).csv', encoding= 'utf-8-sig')
park_Seongdong = pd.read_csv('./data/서울특별시_성동구_도시공원정보_20210930_1632983304518_11837.csv', encoding= 'utf-8-sig')
park_Seongbuk = pd.read_csv('./data/서울특별시_성북구_도시공원정보_20210616_1623821311229_9981.csv', encoding= 'utf-8-sig')
park_Songpa = pd.read_csv('./data/서울특별시_송파구_도시공원정보_20210221_1614749779704_23781.csv', encoding= 'utf-8-sig')
park_Yangcheon = pd.read_csv('./data/서울특별시_양천구_도시공원정보_20210430_1620710785425_20066.csv', encoding= 'utf-8-sig')
park_Yeongdeungpo = pd.read_csv('./data/서울특별시_영등포구_도시공원정보_20210929_1634548360357_10920.csv', encoding= 'utf-8-sig')
park_Yongsan = pd.read_csv('./data/서울특별시_용산구_도시공원정보_20210927_1632788099359_7189.csv', encoding= 'utf-8-sig')
park_Eunpyeong = pd.read_csv('./data/서울특별시_은평구_도시공원정보_20210501_1621212689965_22592.csv', encoding= 'utf-8-sig')
park_Jongno = pd.read_csv('./data/서울특별시_종로구_도시공원정보_20210709_1625794001940_7949.csv', encoding= 'utf-8-sig')
park_Junggu = pd.read_csv('./data/서울특별시_중구_도시공원정보_20211022_1634865794810_7150.csv', encoding= 'utf-8-sig')
park_Jungnang = pd.read_csv('./data/서울특별시_중랑구_도시공원정보_20201112_1605164754016_7760.csv', encoding= 'utf-8-sig')

In [3]:
park_Dobong

,관리번호,공원명,공원구분,소재지도로명주소,소재지지번주소,위도,경도,공원면적,공원보유시설(운동시설),공원보유시설(유희시설),공원보유시설(편익시설),공원보유시설(교양시설),공원보유시설(기타시설),지정고시일,관리기관명,전화번호,데이터기준일자
0,11320-00001,북한산 국립공원,기타,서울특별시 도봉구 도봉산길 88(도봉동),서울특별시 도봉구 도봉1동 산29-2,37.692080,127.031204,8703000,NaN,NaN,"대피소2, 사무소1, 약수터3, 교량 10, 통제소 4, 화장실 20, 파고라 8,...",NaN,NaN,NaN,NaN,NaN,2019-01-01
1,11320-00002,초안산근린공원,근린공원,서울특별시 도봉구 해등로3길 48-11(창동),서울특별시 도봉구 창동 산24 초안산근린공원,37.647426,127.041429,664905,NaN,NaN,"정보문화센터, 배드민턴장, 인조잔디축구장",NaN,NaN,NaN,NaN,NaN,2019-01-01
2,11320-00003,쌍문근린공원,근린공원,서울특별시 도봉구 시루봉로2길 34(쌍문동),서울특별시 도봉구 쌍문동 산80,37.654192,127.029088,328018,NaN,NaN,"배구장, 배드민턴장, 테니스장, 휴게광장,체력단련장, 청소년문화회관",NaN,NaN,NaN,NaN,NaN,2019-01-01
3,11320-00004,월천근린공원,근린공원,서울특별시 도봉구 노해로70길 126,서울특별시 도봉구 창동 28,37.647271,127.052319,10712,NaN,NaN,"화장실, 조합놀이대, 배드민턴장",NaN,NaN,NaN,NaN,NaN,2019-01-01
4,11320-00005,누 원,어린이공원,NaN,서울특별시 도봉구 도봉동 653,37.680396,127.050046,1515,NaN,NaN,"조합놀이대, 의자 등",NaN,NaN,2010-04-01,NaN,NaN,2019-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,11320-00067,도봉마루공원,기타,NaN,서울특별시 도봉구 도봉1동 279,37.687731,127.043916,1361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
67,11320-00068,한전변전소 자투리땅 휴게공원,기타,NaN,서울특별시 도봉구 쌍문3동 346-3,37.648232,127.026829,606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
68,11320-00069,원당샘공원,기타,NaN,서울특별시 도봉구 방학3동 547,37.660753,127.022079,4671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
69,11320-00070,도로개설잔여부 휴게공원,기타,NaN,서울특별시 도봉구 방학1동 725-31,37.661193,127.050512,121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01
70,11320-00071,서울북부지방검찰청주변녹지,기타,NaN,서울특별시 도봉구 도봉2동 626-22,37.675641,127.046681,314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01

In [4]:
park_Gangnam = park_Gangnam[['위도','경도']]
park_Gangdong = park_Gangdong[['위도','경도']]
park_Gangbuk = park_Gangbuk[['위도','경도']]
park_Gangseo = park_Gangseo[['위도','경도']]
park_Gwanak = park_Gwanak[['위도','경도']]
park_Gwangjin = park_Gwangjin[['위도','경도']]
park_Guro = park_Guro[['위도','경도']]
park_Geumcheon = park_Geumcheon[['위도','경도']]
park_Nowon = park_Nowon[['위도','경도']]
park_Dobong = park_Dobong[['위도','경도']]
park_Dongdaemun = park_Dongdaemun[['위도','경도']]
park_Dongjak = park_Dongjak[['위도','경도']]
park_Mapo = park_Mapo[['위도','경도']]
park_Seodaemun = park_Seodaemun[['위도','경도']]
park_Seongdong = park_Seongdong[['위도','경도']]
park_Seongbuk = park_Seongbuk[['위도','경도']]
park_Songpa = park_Songpa[['위도','경도']]
park_Yangcheon = park_Yangcheon[['위도','경도']]
park_Yeongdeungpo = park_Yeongdeungpo[['위도','경도']]
park_Yongsan = park_Yongsan[['위도','경도']]
park_Eunpyeong = park_Eunpyeong[['위도','경도']]
park_Jongno = park_Jongno[['위도','경도']]
park_Junggu = park_Junggu[['위도','경도']]
park_Jungnang = park_Jungnang[['위도','경도']]

In [5]:
park_Gangnam['구'] = '강남구'
park_Gangdong['구'] = '강동구'
park_Gangbuk['구'] = '강북구'
park_Gangseo['구'] = '강서구'
park_Gwanak['구'] = '관악구'
park_Gwangjin['구'] = '광진구'
park_Guro['구']= '구로구'
park_Geumcheon['구'] = '금천구'
park_Nowon['구'] = '노원구'
park_Dobong['구'] = '도봉구'
park_Dongdaemun['구'] = '동대문구'
park_Dongjak['구'] = '동작구'
park_Mapo['구'] = '마포구'
park_Seodaemun['구'] = '서대문구'
park_Seongdong['구'] = '성동구'
park_Seongbuk['구'] = '성북구'
park_Songpa['구'] = '송파구'
park_Yangcheon['구'] = '양천구'
park_Yeongdeungpo['구'] = '영등포구'
park_Yongsan['구'] = '용산구'
park_Eunpyeong['구'] = '은평구'
park_Jongno['구'] = '종로구'
park_Junggu['구'] = '중구'
park_Jungnang['구'] = '중랑구'

In [6]:
park_Dobong

           위도          경도    구
0   37.692080  127.031204  도봉구
1   37.647426  127.041429  도봉구
2   37.654192  127.029088  도봉구
3   37.647271  127.052319  도봉구
4   37.680396  127.050046  도봉구
..        ...         ...  ...
66  37.687731  127.043916  도봉구
67  37.648232  127.026829  도봉구
68  37.660753  127.022079  도봉구
69  37.661193  127.050512  도봉구
70  37.675641  127.046681  도봉구

[71 rows x 3 columns]

In [12]:
park = pd.concat([park_Dobong,park_Dongdaemun,park_Dongjak, park_Eunpyeong,
                 park_Gangbuk,park_Gangdong,park_Gangnam,park_Gangseo,
                 park_Geumcheon,park_Guro,park_Gwanak,park_Gwangjin,
                 park_Jongno,park_Junggu,park_Jungnang,park_Mapo,
                 park_Nowon,park_Seodaemun,park_Seongbuk,park_Seongdong,
                 park_Songpa,park_Yangcheon,park_Yeongdeungpo,park_Yongsan])

In [13]:
park

           위도          경도    구
0   37.692080  127.031204  도봉구
1   37.647426  127.041429  도봉구
2   37.654192  127.029088  도봉구
3   37.647271  127.052319  도봉구
4   37.680396  127.050046  도봉구
..        ...         ...  ...
37  37.534469  127.012481  용산구
38  37.537238  127.013882  용산구
39  37.535685  126.989937  용산구
40  37.524103  126.963575  용산구
41  37.535801  126.989755  용산구

[1772 rows x 3 columns]

In [17]:
park.to_csv('./data/park.csv', header = True, index = False)

In [14]:
! pip install haversine

Collecting haversine
  Downloading haversine-2.5.1-py2.py3-none-any.whl (6.1 kB)
Installing collected packages: haversine
Successfully installed haversine-2.5.1

In [15]:
from haversine import haversine

In [18]:
subway = pd.read_csv('./data/서울교통공사_역주소 및 전화번호.csv')

In [19]:
subway

      연번   역번호  호선      역명         역전화번호                           역주소
0      1   150   1     서울역  02-6110-1331  서울특별시 중구 세종대로 지하 2 (남대문로 5가)
1      2   151   1      시청  02-6110-1321     서울특별시 중구 세종대로 지하 101 (정동)
2      3   152   1      종각  02-6110-1311     서울특별시 종로구 종로 지하 55 (종로1가)
3      4   153   1    종로3가  02-6110-1301    서울특별시 종로구 종로 지하 129 (종로3가)
4      5   154   1    종로5가  02-6110-1291   서울특별시 종로구 종로 지하 216  (종로5가)
..   ...   ...  ..     ...           ...                           ...
287  288  4134   9    송파나루  02-2656-0934             서울특별시 송파구 오금로 165
288  289  4135   9    한성백제  02-2656-0935            서울특별시 송파구 위례성대로 51
289  290  4136   9   올림픽공원  02-2656-0936           서울특별시 송파구 양재대로 1233
290  291  4137   9    둔촌오륜  02-2656-0937            서울특별시 송파구 강동대로 327
291  292  4138   9  중앙보훈병원  02-2656-0938             서울특별시 강동구 명일로 117

[292 rows x 6 columns]

In [21]:
subway['구'] = subway['역주소'].str.split(" ").str[1]

In [22]:
subway = subway.drop(['연번','역번호','호선','역전화번호'], axis = 1)
subway

         역명                           역주소    구
0       서울역  서울특별시 중구 세종대로 지하 2 (남대문로 5가)   중구
1        시청     서울특별시 중구 세종대로 지하 101 (정동)   중구
2        종각     서울특별시 종로구 종로 지하 55 (종로1가)  종로구
3      종로3가    서울특별시 종로구 종로 지하 129 (종로3가)  종로구
4      종로5가   서울특별시 종로구 종로 지하 216  (종로5가)  종로구
..      ...                           ...  ...
287    송파나루             서울특별시 송파구 오금로 165  송파구
288    한성백제            서울특별시 송파구 위례성대로 51  송파구
289   올림픽공원           서울특별시 송파구 양재대로 1233  송파구
290    둔촌오륜            서울특별시 송파구 강동대로 327  송파구
291  중앙보훈병원             서울특별시 강동구 명일로 117  강동구

[292 rows x 3 columns]

In [23]:
subway.isnull().sum()

역명     0
역주소    0
구      0
dtype: int64

In [24]:
 subway['역명'] =subway['역명'].apply(lambda x: x if x[-1]=='역' else x + '역')

In [25]:
subway

          역명                           역주소    구
0        서울역  서울특별시 중구 세종대로 지하 2 (남대문로 5가)   중구
1        시청역     서울특별시 중구 세종대로 지하 101 (정동)   중구
2        종각역     서울특별시 종로구 종로 지하 55 (종로1가)  종로구
3      종로3가역    서울특별시 종로구 종로 지하 129 (종로3가)  종로구
4      종로5가역   서울특별시 종로구 종로 지하 216  (종로5가)  종로구
..       ...                           ...  ...
287    송파나루역             서울특별시 송파구 오금로 165  송파구
288    한성백제역            서울특별시 송파구 위례성대로 51  송파구
289   올림픽공원역           서울특별시 송파구 양재대로 1233  송파구
290    둔촌오륜역            서울특별시 송파구 강동대로 327  송파구
291  중앙보훈병원역             서울특별시 강동구 명일로 117  강동구

[292 rows x 3 columns]

In [26]:
subway = subway.drop_duplicates(['역명'])

In [27]:
subway

          역명                           역주소    구
0        서울역  서울특별시 중구 세종대로 지하 2 (남대문로 5가)   중구
1        시청역     서울특별시 중구 세종대로 지하 101 (정동)   중구
2        종각역     서울특별시 종로구 종로 지하 55 (종로1가)  종로구
3      종로3가역    서울특별시 종로구 종로 지하 129 (종로3가)  종로구
4      종로5가역   서울특별시 종로구 종로 지하 216  (종로5가)  종로구
..       ...                           ...  ...
285    석촌고분역             서울특별시 송파구 삼학사로 53  송파구
287    송파나루역             서울특별시 송파구 오금로 165  송파구
288    한성백제역            서울특별시 송파구 위례성대로 51  송파구
290    둔촌오륜역            서울특별시 송파구 강동대로 327  송파구
291  중앙보훈병원역             서울특별시 강동구 명일로 117  강동구

[253 rows x 3 columns]

In [29]:

for i in range(len(subway)):
    try:
        subway['역주소'][i] = re.sub("\(.*\)|\s-\s.*", '', subway['역주소'][i])
        print(subway['역주소'][i])
    except:
        pass

서울특별시 중구 세종대로 지하 2
서울특별시 중구 세종대로 지하 101
서울특별시 종로구 종로 지하 55
서울특별시 종로구 종로 지하 129
서울특별시 종로구 종로 지하 216
서울특별시 종로구 종로 지하 302
서울특별시 동대문구 왕산로 지하 1
서울특별시 동대문구 왕산로 지하 93
서울특별시 동대문구 왕산로 지하 205
서울특별시 종로구 종로 359
서울특별시 강서구 강서로 지하54
서울특별시 중구 을지로 지하 42
서울특별시 중구 을지로 지하 106
서울특별시 중구 을지로 지하 178
서울특별시 중구 을지로 지하 279
서울특별시 중구 퇴계로 지하 431-1
서울특별시 성동구 왕십리로 지하 374
서울특별시 성동구 왕십리로 지하300
서울특별시 성동구 왕십리로 206
서울특별시 성동구 아차산로 18
서울특별시 성동구 아차산로 100
서울특별시 광진구 아차산로 243
서울특별시 광진구 아차산로 384-1
서울특별시 광진구 강변역로 53
서울특별시 송파구 오금로 20
서울특별시 송파구 올림픽로 지하 265
서울특별시 송파구 올림픽로 지하 140
서울특별시 송파구 올림픽로 지하 23
서울특별시 강남구 테헤란로 지하 538
서울특별시 강남구 테헤란로 지하 340
서울특별시 강남구 테헤란로 지하 156
서울특별시 강남구 강남대로 지하 396
서울특별시 서초구 서초대로 지하 294
서울특별시 서초구 서초대로 지하 233
서울특별시 서초구 방배로 지하 80
서울특별시 동작구 남부순환로 지하 2089
서울특별시 관악구 남부순환로 지하 1928
서울특별시 관악구 남부순환로 지하 1822
서울특별시 관악구 남부순환로 지하 1721
서울특별시 관악구 남부순환로 지하 1614
서울특별시 동작구 대림로 2
서울특별시 구로구 도림천로 477
서울 구로구 구로6동 125-66
서울특별시 구로구 새말로 지하 117-21
서울특별시 영등포구 당산로 지하 28
서울특별시 영등포구 당산로 지하 121
서울특별시 영등포구 당산로 229
서울특별시 마포구 양화로 지하 55
서울특별시 마포구 양화로 지하160
서울특별시 마포구 신촌로 지하 90
서울특별시 마포구 신촌로 지하 180
서울특별시 마포구 신촌로 지하 270
서울특별시 서대문구 서소문로 지하 17
서울특별시 성동구 용답길 86
서울특별시 성동구 천호대로 232
서울특별시 구로구 경인로 67길 160
서울특별시 양천구 목동로3길 지하 33
서울특별시 양천구 중앙로 지하 261
서울특별시 동대문구 천호대로 지하 129
경기도 고양시 덕양구 삼송로 300
서울특별시 은평구 진관2로 지하 15-25
서울특별시 은평구 통일로 지하 849
서울특별시 은평구 통일로 지하 723-1
서울특별시 은평구 통일로 지하 602-1
서울특별시 서대문구 통일로 지하 440-1
서울특별시 서대문구 통일로 지하 361
서울특별시 서대문구 통일로 지하 247
서울특별시 종로구 사직로 지하 130
서울특별시 종로구 율곡로 지하 62
서울특별시 중구 퇴계로 지하 199
서울특별시 중구 동호로 지하 256
서울특별시 중구 다산로 지하 122
서울특별시 성동구 동호로 지하 104
서울특별시 성동구 동호로 21  옥수역
서울특별시 강남구 압구정로 지하 172
서울특별시 강남구 도산대로 지하 102
서울특별시 서초구 잠원로 4길 지하 46
서울특별시 서초구 신반포로 지하 188
서울특별시 서초구 서초중앙로 지하 31
서울특별시 서초구 남부순환로 지하 2585
서울특별시 강남구 남부순환로 지하 2744
서울특별시 강남구 남부순환로 지하 2814
서울특별시 강남구 남부순환로 지하 2952
서울특별시 강남구 남부순환로 지하 3104
서울특별시 강남구 일원로 지하 2
서울특별시 강남구 일원로 지하 121
서울특별시 강남구 광평로 지하 270
서울특별시 송파구 송파대로 지하 257
서울특별시 송파구 중대로 지하 149
서울특별시 송파구 오금로 지하 321
서울특별시 노원구 상계로 305
서울특별시 노원구 상계로 182
서울특별시 노원구 상계로 69-1
서울특별시 도봉구 마들로 11길 77
서울특별시 도봉구 도봉로 지하 486-1
서울특별시 강북구 도봉로 지하 50
서울특별시 강북구 도봉로 지하 198
서울특별시 강북구 도봉로 지하 50
서울특별시 성북구 동소문로 지하 248
서울특별시 성북구 동소문로 지하 102
서울특별시 성북구 삼선교로 지하1
서울특별시 종로구 대학로 지하 120
서울특별시 중구 퇴계로 지하 126
서울특별시 중구 퇴계로 지하 54
서울특별시 용산구 한강대로 지하 306
서울특별시 용산구 한강대로 지하 180
서울특별시 용산구 한강대로 지하 112
서울특별시 용산구 용산동5가 17
서울특별시 동작구 현충로 257
서울특별시 동작구 동작대로 지하 117
서울특별시 서초구 과천대로 지하 816
서울특별시 강서구 금낭화로 지하132
서울특별시 강서구 양천로 22
서울특별시 강서구 하늘길 지하77
서울특별시 강서구 공항대로 지하33
서울특별시 강서구 공항대로 지하163
서울특별시 강서구 공항대로 지하267
서울특별시 강서구 강서로 지하262
서울특별시 강서구 화곡로 지하168
서울특별시 양천구 오목로 지하179
서울특별시 양천구 오목로 지하245
서울특별시 양천구 오목로 지하342
서울특별시 영등포구 양산로 지하21
서울특별시 영등포구 양산로 지하200
서울특별시 영등포구 경인로114가길 지하9
서울특별시 영등포구 여의나루로 지하40
서울특별시 영등포구 여의동로 지하343
서울특별시 마포구 마포대로 지하33
서울특별시 마포구 마포대로 지하100
서울특별시 마포구 마포대로 지하210
서울특별시 종로구 통일로 지하126
서울특별시 종로구 세종대로 지하172
서울특별시 중구 청구로 지하77
서울특별시 성동구 금호로 지하154
서울특별시 성동구 행당로 지하89
서울특별시 성동구 마장로 지하296
서울특별시 성동구 천호대로 지하300
서울특별시 동대문구 천호대로 지하405
서울특별시 광진구 천호대로 지하550
서울특별시 광진구 천호대로 지하657
서울특별시 광진구 아차산로 지하571
서울특별시 강동구 천호대로 지하997
서울특별시 강동구 천호대로 지하1097
서울특별시 강동구 양재대로 지하1480
서울특별시 강동구 양재대로 지하1572
서울특별시 강동구 양재대로 지하1632
서울특별시 강동구 고덕로 지하253
서울특별시 강동구 고덕로 지하359
서울특별시 강동구 양재대로 지하1369
서울특별시 송파구 양재대로 지하1233
서울특별시 송파구 양재대로 지하1127
서울특별시 송파구 오금로 지하402
서울특별시 송파구 오금로 지하499
서울특별시 송파구 마천로57길 지하7
서울특별시 은평구 증산로 지하477
서울특별시 은평구 서오릉로 지하63
서울특별시 은평구 불광로 지하129-1
서울특별시 은평구 연서로 지하137-1
서울특별시 은평구 증산로 지하400 (신사동
서울특별시 은평구 증산로 지하306
서울특별시 은평구 수색로 지하175
서울특별시 마포구 월드컵로 지하240
서울특별시 마포구 월드컵로 지하190
서울특별시 마포구 월드컵로 지하77
서울특별시 마포구 독막로 지하85
서울특별시 마포구 독막로 지하 165
서울특별시 마포구 대흥로 지하 85
서울특별시 용산구 백범로 지하287
서울특별시 용산구 녹사평대로 지하195
서울특별시 용산구 이태원로 지하177
서울특별시 용산구 이태원로 지하287
서울특별시 중구 다산로 지하38
서울특별시 종로구 지봉로 지하112
서울특별시 성북구 보문로 지하116
서울특별시 성북구 고려대로 지하89
서울특별시 성북구 종암로 지하1
서울특별시 성북구 월곡로 지하107
서울특별시 성북구 화랑로 지하157
서울특별시 성북구 화랑로 지하243
서울특별시 노원구 화랑로 지하347-1
서울특별시 노원구 동일로 지하992-1
서울특별시 노원구 화랑로 지하510
서울특별시 중랑구 신내로 지하232
서울특별시 중랑구 용마산로136길 33
경기도 의정부시 동일로 121
서울특별시 도봉구 도봉로 964-40
서울특별시 노원구 동일로 지하1662
서울특별시 노원구 동일로 지하1530-1
서울특별시 노원구 동일로 지하1308-1
서울특별시 노원구 동일로 지하1196
서울특별시 노원구 동일로 지하1074
서울특별시 중랑구 동일로 지하901
서울특별시 중랑구 동일로 지하797
서울특별시 중랑구 망우로 지하 297
서울특별시 중랑구 면목로 지하407
서울특별시 중랑구 사가정로 지하393
서울특별시 중랑구 용마산로 지하227
서울특별시 광진구 능동로 지하417
서울특별시 광진구 능동로 지하210
서울특별시 광진구 능동로 10
서울특별시 강남구 학동로 지하508
서울특별시 강남구 학동로 지하346
서울특별시 강남구 학동로 지하180
서울특별시 강남구 학동로 지하102
서울특별시 서초구 신반포로 지하241
서울특별시 서초구 서초대로 지하103
서울특별시 동작구 사당로 지하310
서울특별시 동작구 사당로 지하218
서울특별시 동작구 상도로 지하 378
서울특별시 동작구 상도로 지하272
서울특별시 동작구 상도로 지하188
서울특별시 동작구 상도로 지하76
서울특별시 동작구 상도로 지하2
서울특별시 영등포구 신풍로 지하27
서울특별시 구로구 도림로 지하7
서울특별시 금천구 벚꽃로 309
경기도 광명시 철산로 지하13
경기도 광명시 오리로 지하980
서울특별시 구로구 오리로 지하1154
서울특별시 구로구 경인로3길 지하64

In [30]:
subway

          역명                    역주소    구
0        서울역    서울특별시 중구 세종대로 지하 2    중구
1        시청역  서울특별시 중구 세종대로 지하 101    중구
2        종각역    서울특별시 종로구 종로 지하 55   종로구
3      종로3가역   서울특별시 종로구 종로 지하 129   종로구
4      종로5가역  서울특별시 종로구 종로 지하 216    종로구
..       ...                    ...  ...
285    석촌고분역      서울특별시 송파구 삼학사로 53  송파구
287    송파나루역      서울특별시 송파구 오금로 165  송파구
288    한성백제역     서울특별시 송파구 위례성대로 51  송파구
290    둔촌오륜역     서울특별시 송파구 강동대로 327  송파구
291  중앙보훈병원역      서울특별시 강동구 명일로 117  강동구

[253 rows x 3 columns]

In [31]:
sub_name = []
for i in subway['역주소']:
    sub_name.append(i)

In [32]:
len(sub_name)

253

In [33]:
gmaps = googlemaps.Client('개인 api')
lat = []
lon = []
for i in sub_name:
    
    location = gmaps.geocode(i, language='ko') 
    
    latitude  = location[0]["geometry"]["location"]["lat"] 
    longitude = location[0]["geometry"]["location"]["lng"] 

    lat.append(latitude)
    lon.append(longitude)
    print(i)

서울특별시 중구 세종대로 지하 2
서울특별시 중구 세종대로 지하 101
서울특별시 종로구 종로 지하 55
서울특별시 종로구 종로 지하 129
서울특별시 종로구 종로 지하 216
서울특별시 종로구 종로 지하 302
서울특별시 동대문구 왕산로 지하 1
서울특별시 동대문구 왕산로 지하 93
서울특별시 동대문구 왕산로 지하 205
서울특별시 종로구 종로 359
서울특별시 강서구 강서로 지하54
서울특별시 중구 을지로 지하 42
서울특별시 중구 을지로 지하 106
서울특별시 중구 을지로 지하 178
서울특별시 중구 을지로 지하 279
서울특별시 중구 퇴계로 지하 431-1
서울특별시 성동구 왕십리로 지하 374
서울특별시 성동구 왕십리로 지하300
서울특별시 성동구 왕십리로 206
서울특별시 성동구 아차산로 18
서울특별시 성동구 아차산로 100
서울특별시 광진구 아차산로 243
서울특별시 광진구 아차산로 384-1
서울특별시 광진구 강변역로 53
서울특별시 송파구 오금로 20
서울특별시 송파구 올림픽로 지하 265
서울특별시 송파구 올림픽로 지하 140
서울특별시 송파구 올림픽로 지하 23
서울특별시 강남구 테헤란로 지하 538
서울특별시 강남구 테헤란로 지하 340
서울특별시 강남구 테헤란로 지하 156
서울특별시 강남구 강남대로 지하 396
서울특별시 서초구 서초대로 지하 294
서울특별시 서초구 서초대로 지하 233
서울특별시 서초구 방배로 지하 80
서울특별시 동작구 남부순환로 지하 2089
서울특별시 관악구 남부순환로 지하 1928
서울특별시 관악구 남부순환로 지하 1822
서울특별시 관악구 남부순환로 지하 1721
서울특별시 관악구 남부순환로 지하 1614
서울특별시 동작구 대림로 2
서울특별시 구로구 도림천로 477
서울 구로구 구로6동 125-66
서울특별시 구로구 새말로 지하 117-21
서울특별시 영등포구 당산로 지하 28
서울특별시 영등포구 당산로 지하 121
서울특별시 영등포구 당산로 229
서울특별시 마포구 양화로 지하 55
서울특별시 마포구 양화로 지하160
서울특별시 마포구 신촌로 지하 90
서울특별시 마포구 신촌로 지하 180
서울특별시 마포구 신촌로 지하 270
서울특별시 서대문구 서소문로 지하 17
서울특별시 성동구 용답길 86
서울특별시 성동구 천호대로 232
서울특별시 구로구 경인로 67길 160
서울특별시 양천구 목동로3길 지하 33
서울특별시 양천구 중앙로 지하 261
서울특별시 동대문구 천호대로 지하 129
경기도 고양시 덕양구 삼송로 300
서울특별시 은평구 진관2로 지하 15-25
서울특별시 은평구 통일로 지하 849
서울특별시 은평구 통일로 지하 723-1
서울특별시 은평구 통일로 지하 602-1
서울특별시 서대문구 통일로 지하 440-1
서울특별시 서대문구 통일로 지하 361
서울특별시 서대문구 통일로 지하 247
서울특별시 종로구 사직로 지하 130
서울특별시 종로구 율곡로 지하 62
서울특별시 중구 퇴계로 지하 199
서울특별시 중구 동호로 지하 256
서울특별시 중구 다산로 지하 122
서울특별시 성동구 동호로 지하 104
서울특별시 성동구 동호로 21  옥수역
서울특별시 강남구 압구정로 지하 172
서울특별시 강남구 도산대로 지하 102
서울특별시 서초구 잠원로 4길 지하 46
서울특별시 서초구 신반포로 지하 188
서울특별시 서초구 서초중앙로 지하 31
서울특별시 서초구 남부순환로 지하 2585
서울특별시 강남구 남부순환로 지하 2744
서울특별시 강남구 남부순환로 지하 2814
서울특별시 강남구 남부순환로 지하 2952
서울특별시 강남구 남부순환로 지하 3104
서울특별시 강남구 일원로 지하 2
서울특별시 강남구 일원로 지하 121
서울특별시 강남구 광평로 지하 270
서울특별시 송파구 송파대로 지하 257
서울특별시 송파구 중대로 지하 149
서울특별시 송파구 오금로 지하 321
서울특별시 노원구 상계로 305
서울특별시 노원구 상계로 182
서울특별시 노원구 상계로 69-1
서울특별시 도봉구 마들로 11길 77
서울특별시 도봉구 도봉로 지하 486-1
서울특별시 강북구 도봉로 지하 50
서울특별시 강북구 도봉로 지하 198
서울특별시 강북구 도봉로 지하 50
서울특별시 성북구 동소문로 지하 248
서울특별시 성북구 동소문로 지하 102
서울특별시 성북구 삼선교로 지하1
서울특별시 종로구 대학로 지하 120
서울특별시 중구 퇴계로 지하 126
서울특별시 중구 퇴계로 지하 54
서울특별시 용산구 한강대로 지하 306
서울특별시 용산구 한강대로 지하 180
서울특별시 용산구 한강대로 지하 112
서울특별시 용산구 용산동5가 17
서울특별시 동작구 현충로 257
서울특별시 동작구 동작대로 지하 117
서울특별시 서초구 과천대로 지하 816
서울특별시 강서구 금낭화로 지하132
서울특별시 강서구 양천로 22
서울특별시 강서구 하늘길 지하77
서울특별시 강서구 공항대로 지하33
서울특별시 강서구 공항대로 지하163
서울특별시 강서구 공항대로 지하267
서울특별시 강서구 강서로 지하262
서울특별시 강서구 화곡로 지하168
서울특별시 양천구 오목로 지하179
서울특별시 양천구 오목로 지하245
서울특별시 양천구 오목로 지하342
서울특별시 영등포구 양산로 지하21
서울특별시 영등포구 양산로 지하200
서울특별시 영등포구 경인로114가길 지하9
서울특별시 영등포구 여의나루로 지하40
서울특별시 영등포구 여의동로 지하343
서울특별시 마포구 마포대로 지하33
서울특별시 마포구 마포대로 지하100
서울특별시 마포구 마포대로 지하210
서울특별시 종로구 통일로 지하126
서울특별시 종로구 세종대로 지하172
서울특별시 중구 청구로 지하77
서울특별시 성동구 금호로 지하154
서울특별시 성동구 행당로 지하89
서울특별시 성동구 마장로 지하296
서울특별시 성동구 천호대로 지하300
서울특별시 동대문구 천호대로 지하405
서울특별시 광진구 천호대로 지하550
서울특별시 광진구 천호대로 지하657
서울특별시 광진구 아차산로 지하571
서울특별시 강동구 천호대로 지하997
서울특별시 강동구 천호대로 지하1097
서울특별시 강동구 양재대로 지하1480
서울특별시 강동구 양재대로 지하1572
서울특별시 강동구 양재대로 지하1632
서울특별시 강동구 고덕로 지하253
서울특별시 강동구 고덕로 지하359
서울특별시 강동구 양재대로 지하1369
서울특별시 송파구 양재대로 지하1233
서울특별시 송파구 양재대로 지하1127
서울특별시 송파구 오금로 지하402
서울특별시 송파구 오금로 지하499
서울특별시 송파구 마천로57길 지하7
서울특별시 은평구 증산로 지하477
서울특별시 은평구 서오릉로 지하63
서울특별시 은평구 불광로 지하129-1
서울특별시 은평구 연서로 지하137-1
서울특별시 은평구 증산로 지하400 (신사동
서울특별시 은평구 증산로 지하306
서울특별시 은평구 수색로 지하175
서울특별시 마포구 월드컵로 지하240
서울특별시 마포구 월드컵로 지하190
서울특별시 마포구 월드컵로 지하77
서울특별시 마포구 독막로 지하85
서울특별시 마포구 독막로 지하 165
서울특별시 마포구 대흥로 지하 85
서울특별시 용산구 백범로 지하287
서울특별시 용산구 녹사평대로 지하195
서울특별시 용산구 이태원로 지하177
서울특별시 용산구 이태원로 지하287
서울특별시 중구 다산로 지하38
서울특별시 종로구 지봉로 지하112
서울특별시 성북구 보문로 지하116
서울특별시 성북구 고려대로 지하89
서울특별시 성북구 종암로 지하1
서울특별시 성북구 월곡로 지하107
서울특별시 성북구 화랑로 지하157
서울특별시 성북구 화랑로 지하243
서울특별시 노원구 화랑로 지하347-1
서울특별시 노원구 동일로 지하992-1
서울특별시 노원구 화랑로 지하510
서울특별시 중랑구 신내로 지하232
서울특별시 중랑구 용마산로136길 33
경기도 의정부시 동일로 121
서울특별시 도봉구 도봉로 964-40
서울특별시 노원구 동일로 지하1662
서울특별시 노원구 동일로 지하1530-1
서울특별시 노원구 동일로 지하1308-1
서울특별시 노원구 동일로 지하1196
서울특별시 노원구 동일로 지하1074
서울특별시 중랑구 동일로 지하901
서울특별시 중랑구 동일로 지하797
서울특별시 중랑구 망우로 지하 297
서울특별시 중랑구 면목로 지하407
서울특별시 중랑구 사가정로 지하393
서울특별시 중랑구 용마산로 지하227
서울특별시 광진구 능동로 지하417
서울특별시 광진구 능동로 지하210
서울특별시 광진구 능동로 10
서울특별시 강남구 학동로 지하508
서울특별시 강남구 학동로 지하346
서울특별시 강남구 학동로 지하180
서울특별시 강남구 학동로 지하102
서울특별시 서초구 신반포로 지하241
서울특별시 서초구 서초대로 지하103
서울특별시 동작구 사당로 지하310
서울특별시 동작구 사당로 지하218
서울특별시 동작구 상도로 지하 378
서울특별시 동작구 상도로 지하272
서울특별시 동작구 상도로 지하188
서울특별시 동작구 상도로 지하76
서울특별시 동작구 상도로 지하2
서울특별시 영등포구 신풍로 지하27
서울특별시 구로구 도림로 지하7
서울특별시 금천구 벚꽃로 309
경기도 광명시 철산로 지하13
경기도 광명시 오리로 지하980
서울특별시 구로구 오리로 지하1154
서울특별시 구로구 경인로3길 지하64
경기도 부천시 길주로 626
경기도 부천시 길주로 지하 502
경기도 부천시 길주로 지하 406
경기도 부천시 길주로 314
경기도 부천시 길주로 202
경기도 부천시 길주로 104
인천광역시 부평구 길주로 지하713 (삼산동)
인천광역시 부평구 길주로 지하623 (삼산동)
인천광역시 부평구 길주로 지하527(갈산동)
서울특별시 강동구 올림픽로 지하776 (암사동)
서울특별시 강동구 올림픽로 지하550 (성내동)
서울특별시 송파구 올림픽로 지하383
서울특별시 송파구 송파대로 지하439 (석촌동)
서울특별시 송파구 송파대로 지하354 (가락동)
서울특별시 송파구 송파대로 지하179 (문정동)
서울특별시 송파구 송파대로 지하82 (장지동)
서울특별시 송파구 송파대로 지하6 (장지동)
경기도 성남시 수정구 수정로 지하365(신흥동)
경기도 성남시 수정구 산성대로 지하 445
경기도 성남시 수정구 산성대로 지하365 (신흥동)
경기도 성남시 수정구 산성대로 지하280 (신흥동)
경기도 성남시 수정구 산성대로 지하200 (수진동)
경기도 성남시 수정구 산성대로 지하100 (수진동)
서울특별시 강남구 봉은사로 지하 201
서울특별시 강남구 선릉로 지하 580
서울특별시 강남구 봉은사로 지하 501
서울특별시 강남구 봉은사로 지하 601
서울특별시 송파구 백제고분로 187
서울특별시 송파구 삼학사로 53
서울특별시 송파구 오금로 165
서울특별시 송파구 위례성대로 51
서울특별시 송파구 강동대로 327
서울특별시 강동구 명일로 117

In [34]:
subway['위도'] = lat
subway['경도'] = lon
subway

역명     0
역주소    0
구      0
위도     0
경도     0
dtype: int64

In [36]:
subway.to_csv('./data/subway.csv', header = True, index = False)